### ISSUE TITLE
Does flpc supports look-around, including look-ahead and look-behind?

### ISSUE THREAD

**Issue by prakhar7184** [itsmeadarsh2008/flpc#4]
I have a case where I need to use "not" feature of regular expression like (?! value ) that means value should not be there. So can you please help me with any example pattern to use this case or help me out.
Thanks
Prakhar

**Comment by itsmeadarsh2008** [comment]
The regex crate does not support it, so I can't help you. This project aims to wrap the regex crate for performance use cases. Thus, there may be features that Python supports but rust regex doesn't.
```
PS D:\dev> python .\main.py
Traceback (most recent call last):
  File "D:\dev\main.py", line 13, in <module>
    matches = match_pattern(pattern, text)
  File "D:\dev\main.py", line 5, in match_pattern
    compiled_pattern = re.compile(pattern)
ValueError: regex parse error:
    apple(?= pie)
         ^^^
error: look-around, including look-ahead and look-behind, is not supported
```
